title: Ketan Sondagar
logo: /assets/img/profile.jpg
email: sondagarketan1999@gmail.com
description: Experienced Full stack Web Developer 
favicon: true
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/ketansondagar

